# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets



class Login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1020, 624)
        login.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1021, 80))
        self.headerFrame.setAutoFillBackground(False)
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label = QtWidgets.QLabel(self.headerFrame)
        self.label.setGeometry(QtCore.QRect(390, 0, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 100, 171, 161))
        self.label_2.setStyleSheet("border-image: url(:/iconoUsuario/IconoUsuario.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.userTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.userTextEdit.setGeometry(QtCore.QRect(380, 310, 281, 41))
        self.userTextEdit.setObjectName("userTextEdit")
        self.passwordTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordTextEdit.setGeometry(QtCore.QRect(380, 390, 281, 41))
        self.passwordTextEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhSensitiveData)
        self.passwordTextEdit.setObjectName("passwordTextEdit")
        self.passwordTextEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 290, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 370, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 460, 111, 28))
        self.pushButton.setObjectName("pushButton")
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 120, 131, 131))
        self.label_5.setStyleSheet("border-image: url(:/userIcon/IconoUsuario.png);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 430, 241, 41))
        self.label_6.setStyleSheet("color:red;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)
     
   

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.label.setText(_translate("login", "LogisTICS"))
        self.label_3.setText(_translate("login", "Usuario"))
        self.label_4.setText(_translate("login", "Contraseña"))
        self.pushButton.setText(_translate("login", "Iniciar Sesión"))
        self.label_5.setText(_translate("login", "TextLabel"))

        
    
from iconos import loginIcon_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
