# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuReportes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuReportes(object):
    def setupUi(self, menuReportes):
        menuReportes.setObjectName("menuReportes")
        menuReportes.resize(1151, 708)
        self.centralwidget = QtWidgets.QWidget(menuReportes)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1151, 91))
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label = QtWidgets.QLabel(self.headerFrame)
        self.label.setGeometry(QtCore.QRect(460, 10, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 90, 1151, 651))
        self.frame.setStyleSheet("background-color: rgb(255, 248, 250);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.reporteVentaBtn = QtWidgets.QPushButton(self.frame)
        self.reporteVentaBtn.setGeometry(QtCore.QRect(740, 120, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reporteVentaBtn.setFont(font)
        self.reporteVentaBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.reporteVentaBtn.setObjectName("reporteVentaBtn")
        self.reportesTable = QtWidgets.QTableWidget(self.frame)
        self.reportesTable.setGeometry(QtCore.QRect(40, 120, 511, 192))
        self.reportesTable.setObjectName("reportesTable")
        self.reportesTable.setColumnCount(4)
        self.reportesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.reportesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportesTable.setHorizontalHeaderItem(3, item)
        self.analisisGraficoBtn = QtWidgets.QPushButton(self.frame)
        self.analisisGraficoBtn.setGeometry(QtCore.QRect(740, 210, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.analisisGraficoBtn.setFont(font)
        self.analisisGraficoBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.analisisGraficoBtn.setObjectName("analisisGraficoBtn")
        self.buscarReporteText = QtWidgets.QPlainTextEdit(self.frame)
        self.buscarReporteText.setGeometry(QtCore.QRect(740, 300, 161, 51))
        self.buscarReporteText.setObjectName("buscarReporteText")
        self.buscarReporteBtn = QtWidgets.QPushButton(self.frame)
        self.buscarReporteBtn.setGeometry(QtCore.QRect(910, 300, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buscarReporteBtn.setFont(font)
        self.buscarReporteBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.buscarReporteBtn.setObjectName("buscarReporteBtn")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        menuReportes.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(menuReportes)
        self.statusbar.setObjectName("statusbar")
        menuReportes.setStatusBar(self.statusbar)

        self.retranslateUi(menuReportes)
        QtCore.QMetaObject.connectSlotsByName(menuReportes)

    def retranslateUi(self, menuReportes):
        _translate = QtCore.QCoreApplication.translate
        menuReportes.setWindowTitle(_translate("menuReportes", "MainWindow"))
        self.label.setText(_translate("menuReportes", "Reportes"))
        self.reporteVentaBtn.setText(_translate("menuReportes", "Generar Reporte de Venta"))
        item = self.reportesTable.horizontalHeaderItem(0)
        item.setText(_translate("menuReportes", "ID Reporte"))
        item = self.reportesTable.horizontalHeaderItem(1)
        item.setText(_translate("menuReportes", "Autor"))
        item = self.reportesTable.horizontalHeaderItem(2)
        item.setText(_translate("menuReportes", "Motivo"))
        item = self.reportesTable.horizontalHeaderItem(3)
        item.setText(_translate("menuReportes", "Fecha"))
        self.analisisGraficoBtn.setText(_translate("menuReportes", "Análisis Gráfico"))
        self.buscarReporteBtn.setText(_translate("menuReportes", "Buscar"))
        self.label_2.setText(_translate("menuReportes", "Historial Reportes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menuReportes = QtWidgets.QMainWindow()
    ui = Ui_menuReportes()
    ui.setupUi(menuReportes)
    menuReportes.show()
    sys.exit(app.exec_())
