# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formularioProducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from helpers import productHelpers

class FormularioProducto(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 711, 91))
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label_3 = QtWidgets.QLabel(self.headerFrame)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 701, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.FormularioProducto = QtWidgets.QFrame(self.centralwidget)
        self.FormularioProducto.setGeometry(QtCore.QRect(0, 90, 701, 880))
        self.FormularioProducto.setStyleSheet("background-color: rgb(255, 248, 249);")
        self.FormularioProducto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FormularioProducto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FormularioProducto.setObjectName("FormularioProducto")
        self.label_12 = QtWidgets.QLabel(self.FormularioProducto)
        self.label_12.setGeometry(QtCore.QRect(20, 200, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.FormularioProducto)
        self.label_13.setGeometry(QtCore.QRect(20, 280, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_18 = QtWidgets.QLabel(self.FormularioProducto)
        self.label_18.setGeometry(QtCore.QRect(20, 500, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.distribuidorCombo = QtWidgets.QComboBox(self.FormularioProducto)
        self.distribuidorCombo.setGeometry(QtCore.QRect(250, 490, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.distribuidorCombo.setFont(font)
        self.distribuidorCombo.setObjectName("distribuidorCombo")
        self.distribuidorCombo.addItem("")
        self.distribuidorCombo.addItem("")
        self.distribuidorCombo.addItem("")
        self.label_19 = QtWidgets.QLabel(self.FormularioProducto)
        self.label_19.setGeometry(QtCore.QRect(20, 430, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.precioVentaTxt = QtWidgets.QTextEdit(self.FormularioProducto)
        self.precioVentaTxt.setGeometry(QtCore.QRect(250, 420, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.precioVentaTxt.setFont(font)
        self.precioVentaTxt.setObjectName("precioVentaTxt")
        self.stockInicialTxt = QtWidgets.QTextEdit(self.FormularioProducto)
        self.stockInicialTxt.setGeometry(QtCore.QRect(250,565,260,40))
        self.stockInicialTxt.setFont(font)
        self.codigoProductoTxt = QtWidgets.QTextEdit(self.FormularioProducto)
        self.codigoProductoTxt.setGeometry(QtCore.QRect(250,640,260,40))
        self.codigoProductoTxt.setFont(font)
        self.addBtn = QtWidgets.QPushButton(self.FormularioProducto)
        self.addBtn.setGeometry(QtCore.QRect(250, 700, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addBtn.setFont(font)
        self.addBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(34, 170, 32);")
        self.addBtn.setObjectName("addBtn")
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.productoTxt = QtWidgets.QTextEdit(self.FormularioProducto)
        self.productoTxt.setGeometry(QtCore.QRect(250, 190, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productoTxt.setFont(font)
        self.productoTxt.setObjectName("productoTxt")
        self.descripcionTxt = QtWidgets.QTextEdit(self.FormularioProducto)
        self.descripcionTxt.setGeometry(QtCore.QRect(250, 275, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descripcionTxt.setFont(font)
        self.descripcionTxt.setObjectName("descripcionTxt")
        self.regresarBtn = QtWidgets.QPushButton(self.headerFrame)
        self.regresarBtn.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.regresarBtn.setStyleSheet("border-image: url(:/iconoProducto_rc/iconoRegresar.png);")
        self.regresarBtn.setText("")
        self.regresarBtn.setObjectName("regresarBtn")
        self.regresarBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_20 = QtWidgets.QLabel(self.FormularioProducto)
        self.label_20.setGeometry(QtCore.QRect(20, 350, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.stockLabel = QtWidgets.QLabel(self.FormularioProducto)
        self.stockLabel.setObjectName("stockLabel")
        self.stockLabel.setFont(font)
        self.stockLabel.setText("")
        self.stockLabel.setGeometry(20,575,141,31)
        self.codigoProductoLabel = QtWidgets.QLabel(self.FormularioProducto)
        self.codigoProductoLabel.setFont(font)
        self.codigoProductoLabel.setText("")
        self.codigoProductoLabel.setGeometry(20,650,150,35)
        self.precioCompraTxt = QtWidgets.QTextEdit(self.FormularioProducto)
        self.precioCompraTxt.setGeometry(QtCore.QRect(250, 350, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.precioCompraTxt.setFont(font)
        self.precioCompraTxt.setObjectName("precioCompraTxt")
        self.label = QtWidgets.QLabel(self.FormularioProducto)
        self.label.setGeometry(QtCore.QRect(300, 30, 131, 121))
        self.label.setStyleSheet("border-image: url(:/iconoProducto_rc/iconoProducto.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

 
        #AÑADIENDO FUNCIONALIDAD A BOTON AÑADIR
        self.addBtn.clicked.connect(lambda: self.add_product())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Añadir Producto"))
        self.label_12.setText(_translate("MainWindow", "Nombre Producto:"))
        self.label_13.setText(_translate("MainWindow", "Descripcion: "))
        self.label_18.setText(_translate("MainWindow", "Distribuidor:"))
        self.distribuidorCombo.setItemText(0, _translate("MainWindow", "Congeladora Mazatlan"))
        self.distribuidorCombo.setItemText(1, _translate("MainWindow", "Mariscos Monterrey"))
        self.distribuidorCombo.setItemText(2, _translate("MainWindow", "Distribuidora Un Nuevo Mundo"))
        self.label_19.setText(_translate("MainWindow", "Precio Venta:"))
        self.addBtn.setText(_translate("MainWindow", "Añadir Producto"))
        self.label_20.setText(_translate("MainWindow", "Precio Compra:"))
        self.stockLabel.setText(_translate("MainWindow", "Stock Inicial:"))
        self.codigoProductoLabel.setText(_translate("MainWindow", "Codigo Producto:"))


#AÑADIENDO A LA BASE DE DATOS   
    def add_product(self):
        self.codigoProducto = self.codigoProductoTxt.toPlainText()
        self.producto = self.productoTxt.toPlainText()
        self.descripcion = self.descripcionTxt.toPlainText()
        self.precioVenta = self.precioVentaTxt.toPlainText()
        self.precioCompra = self.precioCompraTxt.toPlainText()
        self.distribuidor = self.distribuidorCombo.currentText()
        self.stockInicial = self.stockInicialTxt.toPlainText()
        if(self.precioVenta == ""):
            self.precioVenta = 0

        if (self.precioCompra == ""):
            self.precioCompra = 0

        if (self.stockInicial == ""):
            self.stockInicial = 0


        if (self.codigoProducto == "" or self.producto == "" or self.descripcion == "" or self.precioVenta==0 or self.precioCompra == 0 or self.distribuidor == "" or self.stockInicial == 0):


            self.msg = QtWidgets.QMessageBox()
            self.msg.setWindowTitle("Error")
            self.msg.setText("Debes llenar todos los campos")
            self.msg.exec_()

        else:
            if(self.precioCompra.isdecimal() == True and self.precioVenta.isdecimal() == True):
                if(self.stockInicial.isdigit() == True and int(self.stockInicial) > 0):
                    helper = productHelpers.ProductHelper(self.codigoProducto,self.producto,self.descripcion,float(self.precioVenta),float(self.precioCompra),self.distribuidor,int(self.stockInicial))
                    helper.insertar()
                    self.msg = QtWidgets.QMessageBox()
                    self.msg.setWindowTitle("Confirmacion Registro")
                    self.msg.setText("Producto Registrado con éxito")
                    self.msg.exec_()
                    self.descripcionTxt.clear()
                    self.precioCompraTxt.clear()
                    self.precioVentaTxt.clear()
                    self.productoTxt.clear()
                    self.stockInicialTxt.clear()
                    self.codigoProductoTxt.clear()
                else:
                    self.stockInicialTxt.clear()
                    self.msg = QtWidgets.QMessageBox()
                    self.msg.setWindowTitle("Error")
                    self.msg.setText("El Stock Inicial debe ser un numero entero mayor a 0")
                    self.msg.exec_()


            else: 
                self.precioCompraTxt.clear()
                self.precioVentaTxt.clear()
                self.msg = QtWidgets.QMessageBox()
                self.msg.setWindowTitle("Error")
                self.msg.setText("Los precios deben de ser un número")
                self.msg.exec_()

                
           


    
        



import Iconos_rc 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = FormularioProducto()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
