# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuDistribuidores.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pymysql import STRING
import distribuidorHelpers


class MenuDistribuidores(object):
    def setupUi(self, MenuDistribuidores):
        MenuDistribuidores.setObjectName("MenuDistribuidores")
        MenuDistribuidores.resize(1148, 622)
        self.centralwidget = QtWidgets.QWidget(MenuDistribuidores)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1151, 91))
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label_3 = QtWidgets.QLabel(self.headerFrame)
        self.label_3.setGeometry(QtCore.QRect(410, 10, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 90, 1151, 621))
        self.frame.setStyleSheet("background-color: rgb(255, 246, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 15, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.nuevoDistribuidorBtn = QtWidgets.QPushButton(self.frame)
        self.nuevoDistribuidorBtn.setGeometry(QtCore.QRect(890, 150, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nuevoDistribuidorBtn.setFont(font)
        self.nuevoDistribuidorBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nuevoDistribuidorBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.nuevoDistribuidorBtn.setObjectName("nuevoDistribuidorBtn")
        self.buscarDistribuidorBtn = QtWidgets.QPushButton(self.frame)
        self.buscarDistribuidorBtn.setGeometry(QtCore.QRect(1020, 400, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buscarDistribuidorBtn.setFont(font)
        self.buscarDistribuidorBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buscarDistribuidorBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.buscarDistribuidorBtn.setObjectName("buscarDistribuidorBtn")
        self.buscarPedidoTxt = QtWidgets.QPlainTextEdit(self.frame)
        self.buscarPedidoTxt.setGeometry(QtCore.QRect(890, 400, 121, 51))
        self.buscarPedidoTxt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.buscarPedidoTxt.setObjectName("buscarPedidoTxt")
        self.mercanciaBtn = QtWidgets.QPushButton(self.frame)
        self.mercanciaBtn.setGeometry(QtCore.QRect(890, 320, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mercanciaBtn.setFont(font)
        self.mercanciaBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mercanciaBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.mercanciaBtn.setObjectName("mercanciaBtn")
        self.actualizarDistribuidorBtn = QtWidgets.QPushButton(self.frame)
        self.actualizarDistribuidorBtn.setGeometry(QtCore.QRect(890, 240, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actualizarDistribuidorBtn.setFont(font)
        self.actualizarDistribuidorBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actualizarDistribuidorBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.actualizarDistribuidorBtn.setObjectName("actualizarDistribuidorBtn")
        self.btnRegresar = QtWidgets.QPushButton(self.headerFrame)
        self.btnRegresar.setGeometry(QtCore.QRect(20, 5, 91, 81))
        self.btnRegresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRegresar.setStyleSheet("border-image: url(:/iconos/iconoRegresar.png);")
        self.btnRegresar.setText("")
        self.btnRegresar.setObjectName("btnRegresar")
        self.distribuidoresTable = QtWidgets.QTableWidget(self.frame)
        self.distribuidoresTable.setGeometry(QtCore.QRect(20, 50, 750, 400))
        self.distribuidoresTable.setObjectName("distribuidoresTable")
        self.distribuidoresTable.setColumnCount(5)
        self.distribuidoresTable.setRowCount(0)

        #AJUSTANDO TAMAÑO DE LAS COLUMNAS.
        self.header = self.distribuidoresTable.horizontalHeader()
        self.header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        self.header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        self.header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)

        item = QtWidgets.QTableWidgetItem()
        self.distribuidoresTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.distribuidoresTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.distribuidoresTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.distribuidoresTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.distribuidoresTable.setHorizontalHeaderItem(4, item)
        MenuDistribuidores.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MenuDistribuidores)
        self.statusbar.setObjectName("statusbar")
        MenuDistribuidores.setStatusBar(self.statusbar)
     

        self.retranslateUi(MenuDistribuidores)
        QtCore.QMetaObject.connectSlotsByName(MenuDistribuidores)

    def retranslateUi(self, MenuDistribuidores):
        _translate = QtCore.QCoreApplication.translate
        MenuDistribuidores.setWindowTitle(_translate("MenuDistribuidores", "MainWindow"))
        self.label_3.setText(_translate("MenuDistribuidores", "Distribuidores"))
        self.label_4.setText(_translate("MenuDistribuidores", "Mis distribuidores"))
        self.nuevoDistribuidorBtn.setText(_translate("MenuDistribuidores", "Nuevo Distribuidor"))
        self.buscarDistribuidorBtn.setText(_translate("MenuDistribuidores", "Buscar"))
        self.mercanciaBtn.setText(_translate("MenuDistribuidores", "Mercancia"))
        self.actualizarDistribuidorBtn.setText(_translate("MenuDistribuidores", "Actualizar Distribuidor"))
        item = self.distribuidoresTable.horizontalHeaderItem(0)
        item.setText(_translate("MenuDistribuidores", "ID "))
        item = self.distribuidoresTable.horizontalHeaderItem(1)
        item.setText(_translate("MenuDistribuidores", "Nombre"))
        item = self.distribuidoresTable.horizontalHeaderItem(2)
        item.setText(_translate("MenuDistribuidores", "Ubicación"))
        item = self.distribuidoresTable.horizontalHeaderItem(3)
        item.setText(_translate("MenuDistribuidores", "Teléfono"))
        item = self.distribuidoresTable.horizontalHeaderItem(4)
        item.setText(_translate("MenuDistribuidores", "Contacto"))

        #MOSTRANDO DATOS DE LA BASE DE DATOS EN LA TABLA DISTRIBUIDORES
        helper = distribuidorHelpers.DistribuidorHelper("","","","")
        listaDistribuidores = helper.mostrar_tabla()
        self.distribuidoresTable.clearContents()
        row = 0
        for distribuidor in listaDistribuidores:
                self.distribuidoresTable.setRowCount(row + 1)
                self.distribuidoresTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(distribuidor[0])))
                self.distribuidoresTable.setItem(row, 1, QtWidgets.QTableWidgetItem(distribuidor[1]))
                self.distribuidoresTable.setItem(row, 2, QtWidgets.QTableWidgetItem(distribuidor[2]))
                self.distribuidoresTable.setItem(row, 3, QtWidgets.QTableWidgetItem(distribuidor[3]))
                self.distribuidoresTable.setItem(row, 4, QtWidgets.QTableWidgetItem(distribuidor[4]))

                row += 1
        
from iconos import iconosDistribuidores_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuDistribuidor = QtWidgets.QMainWindow()
    ui = MenuDistribuidores()
    ui.setupUi(MenuDistribuidor)
    MenuDistribuidor.show()
    sys.exit(app.exec_())
