# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MenuPrincipal(object):
    def setupUi(self, inicio):
        inicio.setObjectName("inicio")
        inicio.resize(1366, 819)
        self.centralwidget = QtWidgets.QWidget(inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1361, 80))
        self.headerFrame.setAcceptDrops(False)
        self.headerFrame.setAutoFillBackground(False)
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label = QtWidgets.QLabel(self.headerFrame)
        self.label.setGeometry(QtCore.QRect(470, 10, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.contentFrame = QtWidgets.QFrame(self.centralwidget)
        self.contentFrame.setGeometry(QtCore.QRect(0, 80, 1381, 741))
        self.contentFrame.setStyleSheet("background-color: rgb(255, 251, 252);")
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.label_2 = QtWidgets.QLabel(self.contentFrame)
        self.label_2.setGeometry(QtCore.QRect(410, 350, 171, 171))
        self.label_2.setStyleSheet("border-image: url(:/iconos/iconoAnalisisGrafico.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.contentFrame)
        self.label_3.setGeometry(QtCore.QRect(800, 360, 171, 171))
        self.label_3.setStyleSheet("border-image: url(:/iconos/distribuidr.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.contentFrame)
        self.label_4.setGeometry(QtCore.QRect(1000, 30, 201, 201))
        self.label_4.setStyleSheet("border-image: url(:/iconos/pedidoIcono.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.menuReportesBtn = QtWidgets.QPushButton(self.contentFrame)
        self.menuReportesBtn.setGeometry(QtCore.QRect(190, 250, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuReportesBtn.setFont(font)
        self.menuReportesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuReportesBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.menuReportesBtn.setObjectName("menuReportesBtn")
        self.menuInventarioBtn = QtWidgets.QPushButton(self.contentFrame)
        self.menuInventarioBtn.setGeometry(QtCore.QRect(600, 250, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuInventarioBtn.setFont(font)
        self.menuInventarioBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuInventarioBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.menuInventarioBtn.setObjectName("menuInventarioBtn")
        self.menuPedidosBtn = QtWidgets.QPushButton(self.contentFrame)
        self.menuPedidosBtn.setGeometry(QtCore.QRect(1000, 250, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuPedidosBtn.setFont(font)
        self.menuPedidosBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuPedidosBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.menuPedidosBtn.setObjectName("menuPedidosBtn")
        self.menuAnalisisGraficoBtn = QtWidgets.QPushButton(self.contentFrame)
        self.menuAnalisisGraficoBtn.setGeometry(QtCore.QRect(390, 560, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuAnalisisGraficoBtn.setFont(font)
        self.menuAnalisisGraficoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuAnalisisGraficoBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.menuAnalisisGraficoBtn.setObjectName("menuAnalisisGraficoBtn")
        self.menuDistribuidoresBtn = QtWidgets.QPushButton(self.contentFrame)
        self.menuDistribuidoresBtn.setGeometry(QtCore.QRect(780, 560, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuDistribuidoresBtn.setFont(font)
        self.menuDistribuidoresBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuDistribuidoresBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.menuDistribuidoresBtn.setObjectName("menuDistribuidoresBtn")
        self.label_5 = QtWidgets.QLabel(self.contentFrame)
        self.label_5.setGeometry(QtCore.QRect(620, 70, 181, 161))
        self.label_5.setStyleSheet("border-image: url(:/iconos/inventarioIcono.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.contentFrame)
        self.label_6.setGeometry(QtCore.QRect(210, 70, 171, 151))
        self.label_6.setStyleSheet("border-image: url(:/iconos/reporteVenta.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        inicio.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(inicio)
        self.statusbar.setObjectName("statusbar")
        inicio.setStatusBar(self.statusbar)

        self.retranslateUi(inicio)
        QtCore.QMetaObject.connectSlotsByName(inicio)

    def retranslateUi(self, inicio):
        _translate = QtCore.QCoreApplication.translate
        inicio.setWindowTitle(_translate("inicio", "MainWindow"))
        self.label.setText(_translate("inicio", "Bienvenido a LogisTICS"))
        self.menuReportesBtn.setText(_translate("inicio", "Reportes y Ventas"))
        self.menuInventarioBtn.setText(_translate("inicio", "Inventario"))
        self.menuPedidosBtn.setText(_translate("inicio", "Pedidos"))
        self.menuAnalisisGraficoBtn.setText(_translate("inicio", "Análisis Gráfico"))
        self.menuDistribuidoresBtn.setText(_translate("inicio", "Distribuidores"))
from iconos import iconosMenuPrincipal_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inicio = QtWidgets.QMainWindow()
    ui = MenuPrincipal()
    ui.setupUi(inicio)
    inicio.show()
    sys.exit(app.exec_())
