# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misInventarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_misInventarios(object):
    def setupUi(self, misInventarios):
        misInventarios.setObjectName("misInventarios")
        misInventarios.resize(1098, 636)
        self.centralwidget = QtWidgets.QWidget(misInventarios)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1101, 80))
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label = QtWidgets.QLabel(self.headerFrame)
        self.label.setGeometry(QtCore.QRect(390, 10, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 80, 1091, 551))
        self.frame.setStyleSheet("background-color: rgb(255, 249, 250);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addProductoBtn = QtWidgets.QPushButton(self.frame)
        self.addProductoBtn.setGeometry(QtCore.QRect(720, 100, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addProductoBtn.setFont(font)
        self.addProductoBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.addProductoBtn.setObjectName("addProductoBtn")
        self.addProductoBtn_2 = QtWidgets.QPushButton(self.frame)
        self.addProductoBtn_2.setGeometry(QtCore.QRect(720, 210, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addProductoBtn_2.setFont(font)
        self.addProductoBtn_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.addProductoBtn_2.setObjectName("addProductoBtn_2")
        self.addProductoBtn_3 = QtWidgets.QPushButton(self.frame)
        self.addProductoBtn_3.setGeometry(QtCore.QRect(720, 320, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addProductoBtn_3.setFont(font)
        self.addProductoBtn_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 136, 135);")
        self.addProductoBtn_3.setObjectName("addProductoBtn_3")
        self.inventarioTable = QtWidgets.QTableWidget(self.frame)
        self.inventarioTable.setGeometry(QtCore.QRect(40, 80, 511, 192))
        self.inventarioTable.setObjectName("inventarioTable")
        self.inventarioTable.setColumnCount(4)
        self.inventarioTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.inventarioTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventarioTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventarioTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventarioTable.setHorizontalHeaderItem(3, item)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        misInventarios.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(misInventarios)
        self.statusbar.setObjectName("statusbar")
        misInventarios.setStatusBar(self.statusbar)

        self.retranslateUi(misInventarios)
        QtCore.QMetaObject.connectSlotsByName(misInventarios)

    def retranslateUi(self, misInventarios):
        _translate = QtCore.QCoreApplication.translate
        misInventarios.setWindowTitle(_translate("misInventarios", "MainWindow"))
        self.label.setText(_translate("misInventarios", "Mis Inventarios"))
        self.addProductoBtn.setText(_translate("misInventarios", "Añadir Inventario"))
        self.addProductoBtn_2.setText(_translate("misInventarios", "Modificar"))
        self.addProductoBtn_3.setText(_translate("misInventarios", "Eliminar"))
        item = self.inventarioTable.horizontalHeaderItem(0)
        item.setText(_translate("misInventarios", "ID Inventario"))
        item = self.inventarioTable.horizontalHeaderItem(1)
        item.setText(_translate("misInventarios", "Ubicacion"))
        item = self.inventarioTable.horizontalHeaderItem(2)
        item.setText(_translate("misInventarios", "Espacio Disponible"))
        item = self.inventarioTable.horizontalHeaderItem(3)
        item.setText(_translate("misInventarios", "Numero Telefónico"))
        self.label_2.setText(_translate("misInventarios", "Inventarios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    misInventarios = QtWidgets.QMainWindow()
    ui = Ui_misInventarios()
    ui.setupUi(misInventarios)
    misInventarios.show()
    sys.exit(app.exec_())
